@startuml
participant User as User
participant "Gateway" as GW
participant "Converter" as converter
participant "Dispatch" as libdispatch
participant "LangDispatch" as langdispatch
participant "Adapter + Impl" as adapter

User -> GW : compute(a, b)
GW -> converter: call_impl(\n  implh,\n  "compute",\n  oif_args)
converter -> libdispatch : call_interface_impl(\n  implh,\n  "compute",\n  oif_args)
libdispatch -> langdispatch : call_impl(\n  implh,\n  "compute",\n  oif_args)
langdispatch -> adapter : compute(arg1, arg2, ...)
@enduml
