name: Build LaTeX document using Latexmk

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures a full Git history is fetched, including LFS objects
        lfs: true       # Enable Git LFS, because images are in LFS

    - name: Compile LaTeX Beamer with latexmk
      uses: xu-cheng/texlive-action@v3
      with:
        run: |
          cd tikz
          pdflatex oif_bindings.tex
          pdflatex pairwise_bindings.tex
          cd ..
          latexmk -pdf -interaction=nonstopmode -halt-on-error talk*.tex

    - name: Rename PDF file
      if: startsWith(github.ref, 'refs/tags/v')
      run: mv talk-mardi-open-interfaces.pdf mardi-open-interfaces_kabanov-rave-ohlberger_${{ github.ref_name }}.pdf

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: mardi-open-interfaces_kabanov-rave-ohlberger_${{ github.ref_name }}.pdf
