name: Build LaTeX document using Latexmk

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    #- name: Install Git LFS  # Git LFS is large file storage for binary files
    #  run: |
    #    sudo apt-get install -y git-lfs
    #    git lfs install

    - name: Install Texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra
        sudo apt-get install -y texlive-latex-recommended texlive-fonts-extra
        sudo apt-get install -y texlive-science
        sudo apt-get install -y latexmk

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures a full Git history is fetched, including LFS objects
        lfs: true       # Enable Git LFS, because images are in LFS

    - name: Compile LaTeX Beamer with latexmk
      run: |
        cd tikz
        pdflatex oif_bindings.tex
        pdflatex pairwise_bindings.tex
        cd ..
        latexmk -pdf -interaction=nonstopmode -halt-on-error talk*.tex

    - name: Rename PDF file
      if: startsWith(github.ref, 'refs/tags/v')
      run: mv talk-mardi-open-interfaces.pdf talk-mardi-open-interfaces-${{ github.ref_name }}.pdf

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: talk-mardi-open-interfaces-${{ github.ref_name }}.pdf
