name: Build LaTeX document using Latexmk

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures a full Git history is fetched, including LFS objects
        lfs: true       # Enable Git LFS, because images are in LFS

    - name: Compile LaTeX Beamer with latexmk
      uses: xu-cheng/texlive-action@v3
      with:
        run: |
          cd tikz
          pdflatex oif_bindings.tex
          pdflatex pairwise_bindings.tex
          cd ..
          latexmk -pdf -interaction=nonstopmode -halt-on-error talk*.tex

    - name: Create annotated tag from branch name
      if: github.ref_type == 'branch' && github.ref_name != 'main' && github.event_name == 'push'
      id: tag
      run: |
        TAG_NAME="v${{ github.ref_name }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "$TAG_NAME" -m "Release $TAG_NAME from branch ${{ github.ref_name }}"
        git push origin "$TAG_NAME"
        echo "name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Rename PDF file
      if: github.ref_type == 'branch' && github.ref_name != 'main' && github.event_name == 'push'
      run: mv talk-mardi-open-interfaces.pdf mardi-open-interfaces_kabanov-rave-ohlberger_${{ steps.tag.outputs.name }}.pdf

    - name: Create release
      if: github.ref_type == 'branch' && github.ref_name != 'main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.name }}
        files: mardi-open-interfaces_kabanov-rave-ohlberger_${{ steps.tag.outputs.name }}.pdf
